version: '3'

services:
  vault-server:
    image: vault:1.7.0
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_DEV_ROOT_TOKEN_ID: unsafe-root-token
    ports:
      - 8200:8200

  vault-cli:
    image: vault:1.7.0
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_ADDR=http://vault-server:8200
    command: >
      sh -c "vault login unsafe-root-token
      && vault auth enable approle
      && vault write auth/approle/role/concourse_role policies=concourse secret_id_ttl=0 token_num_uses=0 token_ttl=0 token_max_ttl=0 secret_id_num_uses=0
      && vault read -format=json auth/approle/role/concourse_role/role-id > /vault-secrets/role.json
      && vault write -format=json -force auth/approle/role/concourse_role/secret-id policies=concourse > /vault-secrets/secret.json
      && vault secrets enable -path/concourse kv"
    volumes:
      - "./vault/secrets:/vault-secrets"
      - "./config:/vault-config"
    depends_on:
      - vault-server

  concourse-db:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=concourse
      - POSTGRES_PASSWORD=concourse_pass
      - POSTGRES_USER=concourse_user
      - PGDATA=/database

  concourse-web:
    image: concourse/concourse:6.4.0
    command: web --vault-auth-param role_id:"${ROLE_ID}" --vault-auth-param secret_id:${SECRET_ID}
    depends_on:
      - concourse-db
      - vault-server
      - vault-cli
    ports:
      - 8090:8090
      - 2222:2222
    volumes:
      - "./keys/web:/concourse-keys"
    environment:
      - CONCOURSE_POSTGRES_HOST=concourse_db
      - CONCOURSE_POSTGRES_USER=concourse_user
      - CONCOURSE_POSTGRES_PASSWORD=concourse_pass
      - CONCOURSE_POSTGRES_DATABASE=concourse
      - CONCOURSE_EXTERNAL_URL=http://localhost:8080
      - CONCOURSE_ADD_LOCAL_USER=nakib:18gs7jWFwm
      - CONCOURSE_BIND_PORT=8080
      - CONCOURSE_VAULT_URL=http://vault-server:8200
      - CONCOUURSE_VAULT_TLS_INSECURE_SKIP_VERIFY="true"

  concourse-worker:
    image: concourse/concourse:6.4.0
    command: worker
    privileged: true
    depends_on:
      - concourse-web
      - concourse-db
      - vault-cli
      - vault-server
    volumes: ["./keys/worker:/concourse/keys"]
    environment:
      - CONCOURSE_TSA_HOST=concourse-web:2222
      - CONCOURSE_GARDEN_NETWORK
