version: '3'

services:
  vault-server:
    image: vault:1.7.0
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_DEV_ROOT_TOKEN_ID: unsafe-root-token
    ports:
      - 8200:8200

  vault-cli:
    image: vault:1.7.0
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_ADDR=http://vault-server:8200
    command: >
      sh -c "vault login unsafe-root-token
      && vault auth enable approle
      && vault write auth/approle/role/concourse_role policies=concourse secret_id_ttl=0 token_num_uses=0 token_ttl=0 token_max_ttl=0 secret_id_num_uses=0
      && vault read -format=json auth/approle/role/concourse_role/role-id > /vault-secrets/role.json
      && vault write -format=json -force auth/approle/role/concourse_role/secret-id policies=concourse > /vault-secrets/secret.json
      && vault secrets enable -path/concourse kv"
    volumes:
      - "./vault/secrets:/vault-secrets"
      - "./config:/vault-config"
    depends_on:
      - vault-server

  concourse-db:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=concourse
      - POSTGRES_PASSWORD=concourse_pass
      - POSTGRES_USER=concourse_user
      - PGDATA=/database
